# Generated by Django 4.1.3 on 2022-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjectImage',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
