# Generated by Django 4.1.3 on 2022-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subject_subjectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherImage',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
