# Generated by Django 4.1.3 on 2022-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_teacher_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherDescription',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
