# Generated by Django 4.1.3 on 2022-12-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_teacher_teacherdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacherFee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
