# Generated by Django 4.1.3 on 2022-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_teacher_teacherfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
