# Generated by Django 4.1.3 on 2022-11-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_class_student_currentclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='CurrentClass',
        ),
    ]
