# Generated by Django 4.1.3 on 2022-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
