# Generated by Django 4.1.3 on 2022-12-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_testimonial_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherenrolment',
            name='subjects',
            field=models.ManyToManyField(blank='True', to='base.subject'),
        ),
    ]
