# Generated by Django 4.1.3 on 2022-12-16 09:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_teacherenrolment_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherenrolment',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherenrolment',
            name='subjects',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
