# Generated by Django 4.1.3 on 2023-01-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_teacherenrolment_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherenrolment',
            name='subjects',
        ),
        migrations.CreateModel(
            name='TeacherEnrolmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('teacherEnrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teacherenrolment')),
            ],
        ),
        migrations.AddField(
            model_name='teacherenrolment',
            name='subjects',
            field=models.ManyToManyField(through='base.TeacherEnrolmentSubject', to='base.subject'),
        ),
    ]
